thehackerwithin/berkeley

- possible_topics/sched.csv
All involved parties agree to the date change.
> switched teaching dates with alex, anders, and greg.

- _posts/2015-01-28-fhs.markdown
repairs some broken links in the 2015-01-28 post.
> fixin' some links

- _posts/2015-02-18-git.markdown
I have a less-than-great commit summary apparently. I don't know how to refactor it into <50 chars, though.
> Added a description of my presentation that I like better

- _posts/2015-02-25-ipython.markdown
> fix omoju miller bio link

- index.md
we've had talks in 2015! this updates the blog to reflect that.
> change previous talks dates to include 2015

- _posts/2015-03-04-matplotlib-and-seaborn.markdown
Adding bio for Sean Wahl. Adding link to repository with the ipython notebook and brief instructions.
> matplotlib portion of the talk

- _posts/2015-03-04-matplotlib-and-seaborn.markdown
I added my bio and a short paragraph on seaborn with a link to the IPython Notebook I'll be using tomorrow!
Cheers,
Caroline
> Adding seaborn info

- _posts/2015-09-09-advanced-git-fall-2015.markdown
bios for kyle and ross are important.
> adds bios for kyle and ross

- _posts/2015-09-16-visualization-demos-fall-2015.markdown
Since today is "lightning talk style" I put the description for what I'm doing under my bio. If that's too clunky it can be moved to the Discussion section
> Added Ross bio and pyqtgraph description to today's (09.16.15) THW post

- _posts/2015-10-28-adv-python-fall-2015.markdown
Sorry for the delay, I updated a bit to be slightly more readable without explanations.
> link to notebook used during yesterday hacker within

- README.md
@katyhuff do you want me to demo that on lightning talk after @staeiou ?
I can do it from @staeiou Computer :-)
> Add link to binder

- python_metaprogramming/DecoratorsMetaclasses.ipynb
@katyhuff @staeiou blah! i was thinking about doing this and I guess i made it halfway through... i want to finish a metaclass example this week. maybe just a lightning talk...
> Lightning talk or talk 

- _posts/2016-03-30-pythonic-plotting-spring-2016.markdown
Just updated my bio info. Thx!
> Qingkai updated the bio info in the posts

- python_mayavi/mayavi_basic.ipynb
- python_mayavi/mayavi_intermediate.ipynb
- python_mayavi/readme.md
Merging the mayavi plotting tutorial for today
> Mayavi Tutorial

- python_line_profiler_f2py/Profile python script and f2py.ipynb
- python_line_profiler_f2py/README.md
- python_line_profiler_f2py/example.py
This is the script for the lightning talk on April 6th 2016 about the python line profiler and f2py.
> Qingkai add line profiler and f2py for lightning talk

- .gitmodules
- build_systems/README.md
don't merge yet, will be updating the submodule and putting some slides up
> WIP: Build systems material

- docs/_posts/2017-01-31-bash-unix-env.md
We can revise with any feedback through this PR...
> Add brief description and links to UNIX/BASH post

- docs/_posts/2017-02-21-git-github.md
In progress.
I was thinking of renaming it "Make DCVS git again" but that might be a bit too much.
> Draft Git Training.

- docs/_posts/2017-02-21-git-github.md
Just fixed a typo and that confusing upstream remote part.
> fixed typos

- docs/_posts/2017-03-07-documentation.md
@nellev and @choldgraf though I was doing Travis,
I thought they were doing Sphinx.
We'll figure it out.
> Fix misunderstanding.

- docs/_posts/2017-03-21-caffe.md
I added instructions for installing and using Caffe docker image
> Instructions for installing caffe docker image

- docs/_posts/2017-04-04-containers-docker.md
Still WIP, hopefully this link will work for people. With apologies for using powerpoint.
> Post link to slides for Docker presentation

- docs/_posts/2017-10-04-github-oss-f17.md
> cool video

- docs/_posts/2017-10-18-dataframes-r-f17.md
- docs/_posts/2017-10-18-utility-r-f17.md
updated description for R session on 10/18
> updated R session

- docs/_posts/2017-11-29-allofplos-f17.md
includes eventbrite link. any way to include the graphic as well?
> adding info for allofplos hackathon

- docs/_posts/2018-01-24-first-sp18.md
> first session agenda

- code_examples/SQL/SQL_Tutorial-0.ipynb
- docs/_posts/2018-02-21-SQL-relationaldatabases.md
This tutorial has some code examples to demonstrate the following
We'll also cover some more qualitative info like
> WIP: DOC: ENH: SQL tutorial and example code for 2018-02-21

- docs/_posts/2018-02-28-TBD.md
- docs/_posts/2018-02-28-intro-d3js-sp18.MD
Created the post, will add code examples soon!
> Signing up for 2/28 D3 session

- docs/_posts/2018-02-28-intro-d3js-sp18.MD
> fix typos in d3 tutorial
